# Map from VTK to enable key names
KEY_MAP = {
    "Esc": "Esc",
    "Tab": "Tab",
    "Backtab": "Backtab",
    "Backspace": "Backspace",
    "Return": "Enter",
    "Enter": "Enter",
    "Insert": "Insert",
    "Delete": "Delete",
    "Pause": "Pause",
    "Print": "Print",
    "Sysreq": "Sysreq",
    "Clear": "Clear",
    "Home": "Home",
    "End": "End",
    "Left": "Left",
    "Up": "Up",
    "Right": "Right",
    "Down": "Down",
    "Prior": "Page Up",
    "Next": "Page Down",
    "Meta": "Meta",
    "Caps_Lock": "Caps Lock",
    "Num_Lock": "Num Lock",
    "Scroll_Lock": "Scroll Lock",
    "F1": "F1",
    "F2": "F2",
    "F3": "F3",
    "F4": "F4",
    "F5": "F5",
    "F6": "F6",
    "F7": "F7",
    "F8": "F8",
    "F9": "F9",
    "F10": "F10",
    "F11": "F11",
    "F12": "F12",
}
