name: Build wheels

on:
  # Make it possible to manually trigger the workflow
  workflow_dispatch:

jobs:
  build-wheels:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out the release commit
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
      if: runner.os == 'Linux'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.12.1

    - name: Archive build
      uses: actions/upload-artifact@v3
      with:
        name: enable_wheels
        path: wheelhouse
        # don't need these kept for long
        retention-days: 7
